[tox]
envlist = py{310,311,312,313},py312-coveralls

[testenv]
deps =
    PyQt6
    pytest
    pytest-qt
    pytest-cov
commands =
    python -m pytest
setenv=
    PYTEST_QT_API=pyqt6
    QT_QPA_PLATFORM=offscreen

[testenv:py312-coveralls]
passenv = GITHUB_*
platform = linux
deps =
    {[testenv]deps}
    coveralls
commands =
    python -m pytest
    coveralls --service=github
