[tox]
envlist = py310,py311,py312,py313,py313-coveralls

[testenv]
deps =
    PyQt6
    pytest
    pytest-qt
    pytest-cov
commands =
    python -m pytest
setenv=
    PYTEST_QT_API=pyqt6
    QT_QPA_PLATFORM=offscreen

[testenv:py313-coveralls]
passenv = GITHUB_*
platform = linux
deps =
    {[testenv]deps}
    coveralls
commands =
    python -m pytest
    coveralls --service=github
